serve:
  port: 4000
  hostname: 0.0.0.0
  playground: true
  cors:
    origin: '*'
    credentials: true
    allowedHeaders: [ 'Authorization', 'Content-Type' ]
    exposedHeaders: ['Authorization']


sources:
  - name: UserService
    handler:
      graphql:
        endpoint: ${USER_SERVICE_URL}
        operationHeaders:
          Authorization: "{context.headers.authorization}"
        timeout: 5000
        retry: 3
  - name: GradeService
    handler:
      graphql:
        endpoint: ${GRADE_SERVICE_URL}
        operationHeaders:
          Authorization: "{context.headers.authorization}"
        timeout: 5000
        retry: 3
  - name: ClassService
    handler:
      graphql:
        endpoint: ${CLASS_SERVICE_URL}
        operationHeaders:
          Authorization: "{context.headers.authorization}"
        timeout: 5000
        retry: 3
transforms:
  - rename:
      renames:
        - from: Query.userService_*
          to: user_*
        - from: Query.gradeService_*
          to: grade_*
        - from: Query.classService_*
          to: class_*
