services:
    user-service:
        build: ./micro-services/user-service
        container_name: user-service
        restart: always
        ports:
            - "8080"
        environment:
            - MONGO_URI=mongodb://mongo-db:27017/users
            - JWT_SECRET=YRMCKrygcXtx1bVpEMcBKIK9LxX8aDUTUQy2XyuLRCbnoPOhxUeIPqIQW01UfC6QgEKETKf2rM9UQnc4FkRSxA
        depends_on:
            - mongo-db
        networks:
            - campus-connect

    grade-service:
        build: ./micro-services/grade-service
        container_name: grade-service
        restart: always
        ports:
            - "8081"
        environment:
            - MONGO_URI=mongodb://mongo-db:27017/grades
            - USER_DB_URI=mongodb://mongo-db:27017/users
            - JWT_SECRET=YRMCKrygcXtx1bVpEMcBKIK9LxX8aDUTUQy2XyuLRCbnoPOhxUeIPqIQW01UfC6QgEKETKf2rM9UQnc4FkRSxA
        depends_on:
            - mongo-db
        networks:
            - campus-connect

    class-service:
        build: ./micro-services/class-service
        container_name: class-service
        restart: always
        ports:
            - "8082"
        environment:
            - MONGO_URI=mongodb://mongo-db:27017/classes
            - USER_DB_URI=mongodb://mongo-db:27017/users
            - JWT_SECRET=YRMCKrygcXtx1bVpEMcBKIK9LxX8aDUTUQy2XyuLRCbnoPOhxUeIPqIQW01UfC6QgEKETKf2rM9UQnc4FkRSxA
        depends_on:
            - mongo-db
            - grade-service
        networks:
            - campus-connect

    mongo-db:
        image: mongo:latest
        container_name: mongo-db
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - campus-connect
    api-gateway:
        build: ./api-gateway
        container_name: api-gateway
        ports:
            - "4000:4000"
        environment:
            - USER_SERVICE_URL=http://user-service:8080/graphql
            - GRADE_SERVICE_URL=http://grade-service:8081/graphql
            - CLASS_SERVICE_URL=http://class-service:8082/graphql
        networks:
            - campus-connect

    frontend:
        build: ./CampusConnect
        container_name: frontend
        restart: always
        environment:
            - VITE_API_BASE_URL=http://localhost:4000/graphql
        ports:
            - "3000"
        networks:
            - campus-connect

    nginx-lb:
        build: ./nginx-lb
        container_name: nginx-lb
        restart: always
        ports:
            -   "80:80"
        depends_on:
            -   api-gateway
        networks:
            - campus-connect



networks:
    campus-connect:
        driver: bridge

volumes:
    mongo-data:
